- menu_name: "Services"

- name: "About"
  url: "/info/"
  title: "About NABPR"

- name: Blog
  url: "/blog/"
  title: "blog"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Dissertation"
  url: "/dissertation/"
  title: "Dissertation Scholarship"

- name: "Give"
  url: "/donate/"
  title: "Give to NABPR"

- name: "Officers"
  url: "/officers/"
  title: "Officers"

- name: "Publications"
  url: "/publications/"
  title: "publications"

- name: "Meetings"
  url: "/meetings/"
  title: "Meetings"

- name: "Membership Dues"
  url: "/membership/membership-dues/"
  title: "Membership Dues"

- name: "Paypal"
  url: "https://paypal.me/nabpr1972"
  title: "The Official NABPR Paypal page"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "Verify SSL"
  url: "https://www.sslshopper.com/ssl-checker.html#hostname=nabpr.org"
  title: "External Verifcation of NABPR's SSL certificate"

- name: "Credits"
  url: "/credits/"
  title: "credits for NABPR"

- name: "Privacy Policy"
  url: "/privacy-policy/"
  title: "Privacy Policy for NABPR"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
