- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "FeedBurner"
  url: "http://feeds.feedburner.com/NABPR"
  title: "Google FeedBurner"

- name: "Verify SSL"
  url: "https://www.sslshopper.com/ssl-checker.html#hostname=nabpr.org"
  title: "External Verifcation of NABPR's SSL certificate"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
